#!/bin/bash
# DESC: lists all added scripts and their uses

echo "commands and their uses"
echo "-----------------------"

echo 

for f in /usr/local/bin/*; do
	[ -f "$f" ] || continue
	grep -q "^# DESC:" "$f" || continue
	name=$(basename "$f")
	desc=$(grep "^# DESC:" "$f" | sed 's/# DESC: //')
	echo "$name  $desc"
        echo
done
